export const ROUTES = {
  Splash: "Splash",

  OnboardingOne: "OnboardingOne",

  OnboardingTwo: "OnboardingTwo",

  Welcome: "Welcome",

  Register: "Register",
  Login: "Login",
  ForgotPassword: "ForgotPassword",
  HealthSetupOne: "HealthSetupOne",
  HealthSetupTwo: "HealthSetupTwo",
  HealthSetupThree: "HealthSetupThree",
  Home: "Home",
  Profile: "Profile",
  EditHealthRecord: "EditHealthRecord",
  Education: "Education",
  EducationDetail: "EducationDetail",
  Quiz: "Quiz",
  QuizDetail: "QuizDetail",
  QuizResult: "QuizResult",
  Exercise: "Exercise",
  ExerciseDetail: "ExerciseDetail",
  Medication: "Medication",
  MedicationCreate: "MedicationCreate",
  MedicationDetail: "MedicationDetail",
  MedicationEdit: "MedicationEdit",
  HealthTips: "HealthTips",
  HealthTipDetail: "HealthTipDetail",
  ChatList: "ChatList",
  ChatDetail: "ChatDetail",
  Notifications: "Notifications",
  Support: "Support",
  ScheduleVisit: "ScheduleVisit",
} as const;